/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login/styles`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/middlewares/middleware`; params?: Router.UnknownInputParams; } | { pathname: `/reportDetails`; params?: Router.UnknownInputParams; } | { pathname: `/reportDetails/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/middlewares/middleware`; params?: Router.UnknownOutputParams; } | { pathname: `/reportDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/reportDetails/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/login/styles${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/home/styles${`?${string}` | `#${string}` | ''}` | `/middlewares/middleware${`?${string}` | `#${string}` | ''}` | `/reportDetails${`?${string}` | `#${string}` | ''}` | `/reportDetails/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login/styles`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/middlewares/middleware`; params?: Router.UnknownInputParams; } | { pathname: `/reportDetails`; params?: Router.UnknownInputParams; } | { pathname: `/reportDetails/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
